### ISSUE TITLE
Assembly reference 'System.Numerics.dll' was not found or is invalid

### ISSUE THREAD

**Issue by davidpodhola** [fsprojects/Fable#35] opened 2016-02-25 12:37 UTC
when compiling `fsx` file on certain machines (without Visual Studio 2015?). Compiling `fsproj` (like the  test one) works correctly.

**Comment by alfonsogarciacaro** [comment] 2016-02-25 13:59
It seems the [`GetProjectOptionsFromScript` method](https://github.com/fsprojects/Fable/blob/master/src/Main.fs#L44-L46) adds many references by default to `fsx` scripts (see image). I've tried removing the core references and it seems the AST can still be retrieved (but there'll be fails if custom references, like NUnit, are removed). Maybe the easiest solution would be to remove the core references but I'd like to check with the F# compiler team first.

<img width="867" alt="screen shot 2016-02-25 at 14 50 13" src="https://cloud.githubusercontent.com/assets/8275461/13321463/6bf36760-dbcf-11e5-966e-663fba54ce12.png">

**Comment by alfonsogarciacaro** [comment] 2016-02-28 22:16
Closing for now. Solution seems a bit messy, and probably it's better to update F# in the machines affected.

**Closed by alfonsogarciacaro** 2016-02-28 22:16 UTC

**Comment by davidpodhola** [comment] 2016-02-29 12:37
Sorry, I do not understand how to update F#. These are two build machines with the latest FSharp installed according to [Option 3](http://fsharp.org/use/windows/).

However [copying 4.5 files from working development machine](http://stackoverflow.com/q/17220615) seems to fix this (I had only .NET 4.6 installed).

Anyway the build is now failing on

```
Starting Target: Plugins (==> MainRelease)
C:\Users\david.podhola\S\Fabel\build\plugins already exists.
FSC with args:[|"--out:build/plugins/Fable.Plugins.NUnit.dll"; "--target:library";
  "plugins/Fable.Plugins.NUnit.fsx"|]
startup (1,1)-(1,81) parameter error Could not resolve this reference. Could not locate the assembly "System.Numerics.dll". Check to make sure the assembly exi
```

**Comment by alfonsogarciacaro** [comment] 2016-02-29 13:01
This looks like a build problem and to be honest I'm not sure I can help: I'm not an expert and I'm not on Windows right now. [These lines](https://github.com/fsprojects/Fable/blob/master/build.fsx#L72-L75) seem to cause the problem which are just calling a FAKE helper method to compile a `.fsx` file.

Sorry for the hassle but, would you mind opening a question in StackOverflow with the problem (cannot compile `fsx` files in your machines because `System.Numerics.dll` is missing)?

**Comment by davidpodhola** [comment] 2016-02-29 18:37
Yes, I think this is related to FAKE. I am still investigating.

BTW running

**Comment by maun** [comment] 2016-05-21 19:59
I followed [this](http://kcieslak.io/Getting-Started-with-Fable-and-Webpack/) guide and also got the error.

```
Start compilation...
F# project contains errors:
> Assembly reference 'System.Numerics.dll' was not found or is invalid: L1 (startup)
```

How can I solve this?

**Comment by alfonsogarciacaro** [comment] 2016-05-21 22:01
I'm very lost with this error because I never could reproduce it myself. It does seem it has something to with the F# installation on some Windows machines. Can you please try with a project (`.fsproj`) instead of a script (`.fsx`)? It used to be a hassle to create projects outside VS but now it's much easier with Ionide and/or Forge :)

**Comment by maun** [comment] 2016-05-22 06:57
I created a project with yeoman and now get this error:
```
Start compilation...
F# project contains errors:
> Unable to find the file 'mscorlib.dll' in any of
 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0
 c:\Users\Manuel\Dropbox\Dev\fable-test\src
 C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\: L1 (unknown)
> Unable to find the file 'FSharp.Core.dll' in any of
 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0
 c:\Users\Manuel\Dropbox\Dev\fable-test\src
 C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\: L1 (unknown)
> Unable to find the file 'mscorlib.dll' in any of
 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0
 c:\Users\Manuel\Dropbox\Dev\fable-test\src
 C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\: L1 (unknown)
```

I tried to reinstall the Windows SDK and Net 4.6 SDK from [here](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk), but it was already installed and up to date.

**Comment by alfonsogarciacaro** [comment] 2016-05-22 07:47
I've reported the issue in the FSharp.Compiler.Service repo. Hopefully they can provide some help.

**Comment by maun** [comment] 2016-05-23 20:07
I forgot to install the Microsoft Build Tools 2015, this solved it for me.
(https://www.microsoft.com/de-de/download/confirmation.aspx?id=48159)

**Comment by alfonsogarciacaro** [comment] 2016-05-23 20:36
Great, I'm happy to hear that. This will probably be very useful for people having the same problem in the future :)
