### ISSUE TITLE
Browser.window.setInter fails without any additional information

### ISSUE THREAD

**Issue by vasyl-purchel** [fsprojects/Fable#245] opened 2016-07-10 09:24 UTC
### Description

I'm creating Visual Studio Code extension that need some polling job done, but `Browser.window.setInterval` is failing when called without any exception in debug or when stepping through generated javascript code.

### Code

F# code to reproduce:
```fsharp
#r "../node_modules/fable-core/Fable.Core.dll"
#load "../node_modules/fable-import-vscode/Fable.Import.VSCode.fs"

open Fable.Core
open Fable.Import
open Fable.Import.vscode

let pollingF () =
  window.showInformationMessage "Hello from polling!"
  |> ignore

let helloWorld () =
  Browser.window.setInterval(pollingF, 3000)

let activate (ctx: vscode.ExtensionContext) =
  commands.registerCommand("extension.sayHello", fun _ -> helloWorld() |> unbox)
  |> ctx.subscriptions.Add

Node.exports?activate <- activate
```

Here is generated code:
```javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.activate = exports.helloWorld = exports.pollingF = undefined;

var _vscode = require("vscode");

var pollingF = exports.pollingF = function () {
  _vscode.window.showInformationMessage("Hello from polling!");
};

var helloWorld = exports.helloWorld = function () {
  return window.setInterval(function (arg00_) {
    pollingF(arg00_);
  }, 3000);
};

var activate = exports.activate = function (ctx) {
  (function () {
    return function () {
      var objectArg;
      return objectArg = ctx.subscriptions, function (arg00) {
        objectArg.push(arg00);
      };
    }();
  })()(_vscode.commands.registerCommand("extension.sayHello", function (_arg1) {
    return helloWorld();
  }));
};

exports.activate = function (ctx) {
  activate(ctx);
};
//# sourceMappingURL=extension.js.map
```

### Related information 

* Operating system: **OS X El Capitan 10.11.5**
* VSCode: **1.3.0**
* mono&f#:
```bash
λ mono --version
Mono JIT compiler version 4.4.0 (tarball Wed Jun 15 18:28:03 BST 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen

λ fsharpi

F# Interactive for F# 4.0 (Open Source Edition)
Freely distributed under the Apache 2.0 Open Source License
```

**Comment by alfonsogarciacaro** [comment] 2016-07-10 10:36
On a first look, there seems to be no problem with how Fable translated `window.setInterval`. I tried to reproduce the issue and I my hunch is VS Code doesn't allow using timers without a promise. I changed you `helloWorld` function to the following and it's working:

```fsharp
let helloWorld () =
    let rec infiniteHello() =
        async {
            do! Async.Sleep 3000
            pollingF()
            return! infiniteHello()
        }
    infiniteHello() |> Async.StartAsPromise
```

You can check the whole code here: https://github.com/alfonsogarciacaro/vscode-fable-demo

**Comment by alfonsogarciacaro** [comment] 2016-07-10 10:46
I just received your confirmation that the sample works using `System.Timer` instead so it shouldn't be a problem with promises then. Hmmm, I'm not sure which approach works better. If both `System.Timer` and `Async` work, pick whatever you feel most comfortable with. Also, it'd be ideal if you could rewrite the sample to be used directly in the browser (without VS Code) to see if there's really a problem with `Browser.window.setInterval`.

**Comment by vasyl-purchel** [comment] 2016-07-10 10:46
ok, so from the [DateTime tests](https://github.com/fsprojects/Fable/blob/master/src/tests/DateTimeTests.fs#L532-L569) I got this working (helloWorld2 command works):

```fsharp
#r "../node_modules/fable-core/Fable.Core.dll"
#load "../node_modules/fable-import-vscode/Fable.Import.VSCode.fs"

open Fable.Core
open Fable.Import
open Fable.Import.vscode

let pollingF () =
  printfn "inside pollingF"
  window.showInformationMessage "Hello from polling!"
  |> ignore

let helloWorld () =
  Browser.window.setInterval(pollingF, 3000)

let helloWorld2 (timer:System.Timers.Timer) =
  printfn "inside helloWorld2"
  timer.Start()
  timer.Elapsed.Add(fun _ -> pollingF())

let activate (ctx: vscode.ExtensionContext) =
  commands.registerCommand("extension.sayHello", fun _ -> helloWorld() |> unbox) |> ctx.subscriptions.Add
  let timer = new System.Timers.Timer(300.)
  commands.registerCommand("extension.sayHello2", fun _ -> helloWorld2(timer) |> unbox) |> ctx.subscriptions.Add
  timer |> ctx.subscriptions.Add

Node.exports?activate <- activate
```

for your example it is not using setInterval... so is there a way of using it (I found it used in [here](https://github.com/Microsoft/vsts-vscode/blob/master/src/team-extension.ts#L517-L519))?

**Comment by vasyl-purchel** [comment] 2016-07-10 10:53
ok, I'll try see if it works with browser

**Comment by alfonsogarciacaro** [comment] 2016-07-10 11:05
BTW, I forgot to say that with the last versions of Fable you don't need to do the `Node.exports` trick. So the last line can be safely removed:

```fsharp
Node.exports?activate <- activate
```

**Comment by vasyl-purchel** [comment] 2016-07-10 11:19
good to know that, thanks

also I quickly checked Browser.window.setInterval with fable-react and it works

**Comment by alfonsogarciacaro** [comment] 2016-07-10 11:21
Thanks for the confirmation! It may be a VS Code thing then. As we've more or less found some workarounds for the problem please feel free to close the issue if you want :+1:

**Closed** 2016-07-10 11:52 UTC
