### ISSUE TITLE
SyntaxError: unknown: 'this' is not allowed before super() 

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Fable#65] opened 2016-03-17 12:33 UTC
The following code:
```
type Class1() =
    member val Prop: string = "" with get, set

type Class2() as x =
    inherit Class1()
    do x.Prop <- "Hello"
```

Emits the following errro:
```
{ [SyntaxError: unknown: 'this' is not allowed before super() (This is an error on an internal node. Probably an internal error)] _babel: true }
```

Removing the `as x` and `do x.Prop <- "Hello"` solves the problem.

**Comment by alfonsogarciacaro** [comment] 2016-03-17 14:02
Yeah, I faced that issue to when creating the React example, so I had to create an [additional class](https://github.com/fsprojects/Fable/blob/master/samples/browser/react/public/react-helper.fs#L6-L11) to work around it. Unfortunately the issue is not easy to fix and I didn't have time yet to deal with. I'll leave the issue open to fix it later. For now, you can do some hacking using `Emit` as in the example to call the `this` keyword:

```fsharp

let private [<Emit("this")>] this = obj()

type Class1() =
    member val Prop: string = "" with get, set

type Class2() =
    inherit Class1()
    do this?Prop <- "Hello"
```

**Comment by davidtme** [comment] 2016-03-17 14:05
As always, thanks for your help

**Comment by alfonsogarciacaro** [comment] 2016-03-22 19:56
I've been exploring the issue and it's very difficult to fix as the F# compiler introduces complicated checks when making self references in the constructors. It's probably better not to encourage this coding style so I'm closing the issue, sorry! For cases like declaring initial state in React class components, ad-hoc hacks as the one shown above are still possible.

**Closed by alfonsogarciacaro** 2016-03-22 19:56 UTC
Labels: wontfix

**Comment by Neftedollar** [comment] 2017-01-04 23:03
@alfonsogarciacaro  as I see now with the react-todomvc sample the problem with `this` is solved. 
Am I right?

**Comment by alfonsogarciacaro** [comment] 2017-01-05 06:15
Yeah, at the end I found a workaround 😅 A bit of rubbish code is generated in the JS class constructor though.
