### ISSUE TITLE
Two Modules name 'X' occur in two parts of this assembly

### ISSUE THREAD

**Issue by ritcoder** [fsprojects/Fable#148] opened 2016-05-20 18:24 UTC
### Description

I'm getting a number of errors with fable for a project I'm migrating. Not really sure what I'm doing wrong since `ionide` isn't complaining.

Three distinct errors have been identified

- The namespace or module 'XXX' is not defined
- Lookup on object of indeterminate type based on information ...
- Two modules named 'XXX' occur in two parts of this assembly

What could be the case?

### Repro steps

Please provide the steps required to reproduce the problem

Create app with modules based on `fsx`. If two or more modules re

### Expected behavior

A compiled app

### Actual behavior

I get the error below

````
u:\Work\PlayGround\Fable\CreatingVSCodePlugin\test2>fable
Start compilation...
F# project contains errors:
> The namespace or module 'SystemModels' is not defined: L3 (SystemData.fsx)
> The record label 'apiUrl' is not defined: L7 (SystemData.fsx)
> Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.: L21 (SystemData.fsx)
> The record label 'apiUrl' is not defined: L27 (SystemData.fsx)
> The namespace or module 'Trello' is not defined: L15 (FeedBack.fsx)
> The namespace or module 'SystemModels' is not defined: L17 (FeedBack.fsx)
> The type 'User' is not defined: L81 (FeedBack.fsx)
> The field, constructor or member 'role' is not defined: L87 (FeedBack.fsx)
> The record label 'desc' is not defined: L89 (FeedBack.fsx)
> The field, constructor or member 'user' is not defined: L104 (FeedBack.fsx)
> The field, constructor or member 'trello' is not defined: L104 (FeedBack.fsx)
> The namespace or module 'Trello' is not defined: L105 (FeedBack.fsx)
> The namespace or module 'SystemModels' is not defined: L65 (TopPanel.fsx)
> Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.: L71 (TopPanel.fsx)
> Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.: L73 (TopPanel.fsx)
> Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.: L132 (TopPanel.fsx)
> Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.: L144 (TopPanel.fsx)
> An implementation of the file or module 'SystemData$fsx' has already been given: L1 (systemData.fsx)
> Two modules named 'SystemData' occur in two parts of this assembly: L1 (SystemData.fsx)
````

### Known workarounds

Not sure

### Related information 

* Operating system Windows 10
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by alfonsogarciacaro** [comment] 2016-05-20 18:44
It seems your text in the Repro steps section got cut, could you please edit it? Also, if it's possible for you to upload the project somewhere that would be very helpful to reproduce the problem.

Cheers!

**Comment by ritcoder** [comment] 2016-05-20 21:57
Noted. I'm porting an "urgent" project so logging the issues. When done, I'll go through them and see if I can recreate them. On this, I created an F# project and moved the files there, converting each `fsx` to `fs` (replace `#r` and `#load` with `module xxx` and it worked fine. Might be related to the `fsx` files.

**Comment by alfonsogarciacaro** [comment] 2016-05-21 09:26
I've managed to (partially) reproduce the error with the following set of files:

I've tried to reproduce the error by creating a test script:

```fsharp
// Test.1.fsx
printfn "Hello from Test1"

// Test.2.fsx
printfn "Hello from Test2"

// Test.fsx
#load "Test.1.fsx"
#load "Test.2.fsx"
```

Then the F# compiler complains that there're two modules named `Test`. If I delete the first period (`Test.1.fsx` > `Test1.fsx`) the problem disappears. This is tricky because the error occurs in the parsing phase which is completely delegated to the F# compiler and Fable has not much to do there.

Anyways, I'm happy that it got solved moving to a F# project. Loading files from scripts has some restrictions in F#, so when the structure get's a bit more complicated it's usually better to use a `.fsproj`... even if nobody likes XML anymore ;)

I hope the porting goes well! Please get back in touch if you have any other issue.

**Comment by ritcoder** [comment] 2016-05-21 11:40
In moving to `.fsproj`, I had to switch to visual studio. Will look at `forge` when the porting is done so I can use vscode.

I think the other scenario might be at below (will still have to confirm though) 

````
//sysModel.fsx
...

//sysData.fsx
#load "sysModel.fsx"
...

//myPanel.fsx
#load "sysModel.fsx"
...

//main.fsx
#load "sysData.fsx"
#load "myPanel.fsx"

````

I run into this problem because I though I could treat `#load` like `require`.
I thought if it was possible, those duplicates will just be removed and the code will compile.
When the files because many, I kinda lost track as to who has loaded what fsx so I do not load it again.
`.fsproj` does not have that issue though

**Comment by alfonsogarciacaro** [comment] 2016-05-22 08:29
Not 100% sure but out of memory I think it's not possible (or it's but gives unexpected behaviour) to load a script twice even when just using F# interactive. So in your example above, `sysModel.fsx` shouldn't be loaded twice from two different files. As you said, `#load` doesn't work exactly the same as `require` in Node.

**Comment by ritcoder** [comment] 2016-05-27 11:05
Yes. `#load` isn't the same as `require` but when I was trying it out, assumed `fable` was doing some magic in the background :) . In any case, a page with differences, gotchas, dos and donts might help people testing it out. Wouldn't mind helping out :) .

**Comment by alfonsogarciacaro** [comment] 2016-06-05 13:16
Closing this for now, please reopen it if you can find the way to reproduce it.

But sorry, I just noticed I missed your last comment about a page with differences, gotchas... We're trying to cover these things in the [docs](http://fsprojects.github.io/Fable/docs.html). Of course, please feel free to send a PR to add any information you may deem missing. Docs' source is in markdown format in [this directory](https://github.com/fsprojects/Fable/tree/master/docs/source/docs). Cheers!

**Closed by alfonsogarciacaro** 2016-06-05 13:16 UTC
Labels: bug
