### ISSUE TITLE
NUnit tests with instance members

### ISSUE THREAD

**Issue by fdcastel** [fsprojects/Fable#90] opened 2016-04-02 08:37 UTC
What should be changed in NUnit plugin to make this work?

```
namespace NUnit.Tests

open System
open NUnit.Framework

[<NUnit.Framework.TestFixture>] 
module NUnitTests = 

    [<Test>]
    let ``NUnit static member test``() =
        Assert.AreEqual (3, 1 + 2)
  
    [<NUnit.Framework.TestFixture>] 
    type TestClass() = 

        [<Test>]
        member this.``NUnit instance member test``() =
            Assert.AreEqual (3, 1 + 2)
```

Currently, the plugin transforms only the first test. The second one fails with

`Unexpected member in module <null>: Constructor (...)`

as the plugin is written to only expect F# Modules marked with `[<TestFixture>]`, not classes.

Why I'm asking this?

I'm working in a new plugin to transform Visual Studio Unit Tests, which -- unlike NUnit -- doesn't support static members tests, only instance ones.

But since my noob factor is too damn high for now :), I'm needing a little push here to speed the things up. I'm a bit lost with what Babel transformations should be done at IDeclarePlugin.

**Comment by alfonsogarciacaro** [comment] 2016-04-02 14:56
Interesting, I didn't take that into account :/ I'm trying to find the best way to solve this. Probably it would be enough to change [these lines](https://github.com/fsprojects/Fable/blob/master/src/fable-fsharp/Fable2Babel.fs#L500-L502) as follows:
```
            | Fable.MemberDeclaration m ->
                match m.Kind with
                | Fable.Method _ | Fable.Setter _ -> acc
                | _ ->
                    transformModMember com ctx modIdent m
                    |> consBack acc
```
But I'm afraid this can cause some silent errors (though we should already enough tests to avoid that). Another solution would be to move all the necessary code to the plugin and do the modification there, but this may be a bit cumbersome. What do you think?

**Comment by fdcastel** [comment] 2016-04-02 20:56
To move all the code to plugin would be probably cumbersome (think about having to make plugins for 4 different test frameworks, all of them with a copy of `transformModDecls`?).

It probably means we should improve the plugin API. (maybe some `ITransformPlugin`?)

Anyway... These are only wild guesses. Let me do some tests here. :)

**Comment by fdcastel** [comment] 2016-04-02 21:35
Hm. Nope :( -- With the suggested change the plugin stopped converting methods which have no attributes (e.g. checkTo3dp in ArithmeticTests.fs).

But I think I got what you tried to do. I'll keep trying from here ;)

**Comment by alfonsogarciacaro** [comment] 2016-04-03 23:13
I made an embarrassing mistake there. The modification should actually be as follows:
```
            | Fable.MemberDeclaration m ->
                match m.Kind with
                | Fable.Constructor | Fable.Setter _ -> acc
                | _ ->
                    transformModMember com ctx modIdent m
                    |> consBack acc
```
Before I was ignoring all module methods :( ...I know, I know, more sleep, going to bed now ;)

**Comment by fdcastel** [comment] 2016-04-04 23:40
(Sorry for the delay). This last change indeed solved the problem. :+1: 

In the end, the new plugin turned out to be a blatant copy of NUnit one :) with some minors modifications. It surely helped the fact that both frameworks are _very_ similar:

NUnit tests:

```
open NUnit.Framework

[<TestFixture>] 
module NUnitTests = 

    [<Test>]
    let ``NUnit static member test``() =
        Assert.AreEqual (3, 1 + 2)
  
    [<TestFixture>] 
    type TestClass() = 
        [<Test>]
        member this.``NUnit instance member test``() =
            Assert.AreEqual (3, 1 + 2)
```


Visual Studio tests:

```
open Microsoft.VisualStudio.TestTools.UnitTesting

[<TestClass>]
module VisualStudioTests = 

    [<TestMethod>]
    // This test is not recognized by the framework (Visual Studio 2015 update 1)
    // Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll v14.0.23107.0 
    let ``Visual Studio static member test``() =
        Assert.AreEqual (3, 1 + 2)

    [<TestClass>]
    type testrun() = 
        [<TestMethod>]
        member this.``Visual Studio instance member test``() =
            Assert.AreEqual (3, 1 + 2)
```

I'm making a PR soon. I will put a notice into the code to remember this fact.

BTW: About [this comment](https://github.com/fsprojects/Fable/blob/master/src/plugins/Fable.Plugins.NUnit.fsx#L27), could you elaborate, please?

**Comment by fdcastel** [comment] 2016-04-06 05:24
Fixed in 092f261d69ec0759f21192f649b08d2d2954fc3d.

**Comment by alfonsogarciacaro** [comment] 2016-04-06 08:53
Sorry, I forgot to reply your question about [// TODO: Check method signature](https://github.com/fsprojects/Fable/blob/master/src/plugins/Fable.Plugins.NUnit.fsx#L34) comment. When creating the tests at the beginning (mostly by copy&pasting from FunScript) sometimes I forgot to remove the argument from the method. NUnit complains very quickly if you're not using `TestCaseAttribute` (which would be very useful but it's not available yet) but Mocha just hangs up and sometimes it took me a while to find out the argument was the culprit so I thought it'd be better to fail right away if you're passing a method with arguments... something I obviously forgot to do too ;)

**Comment by fdcastel** [comment] 2016-04-07 08:47
Thanks for the info, That was [an easy one](#102) :)

**Comment by fdcastel** [comment] 2016-04-07 09:10
Now, this one is giving me headaches: :sweat: 

```fsharp
open NUnit.Framework

[<TestFixture>] 
module NUnitTests = 
    let staticTest1result = 3
    let staticCalc1Result() = 1 + 2

    let staticTest2result = 4
    let staticCalc2Result() = 2 + 2

    [<Test>]
    let ``NUnit static member test 1``() =
        Assert.AreEqual (staticTest1result, staticCalc1Result())
  
    [<Test>]
    let ``NUnit static member test 2``() =
        Assert.AreEqual (staticTest2result, staticCalc2Result())

    [<TestFixture>] 
    type TestClass() = 
        let test1result = 3       // (1)
        let calc1Result() = 1 + 2

        member this.test2result = 4
        member this.calc2Result() = 2 + 2

        [<Test>]
        member this.``NUnit instance member test 1``() =
            Assert.AreEqual (test1result, calc1Result())   // (2)

        [<Test>]
        member this.``NUnit instance member test 2``() =
            Assert.AreEqual (this.test2result, this.calc2Result())   // (2)
```

All the "static" declarations are fine. Problem is (again) with the instance members. After compiling (with NUnit plugin) the generated code

```javascript
    describe("TestClass", function () {
        var test2result = 4;

        var calc2Result = function () {
            return 2 + 2;
        };

        it("NUnit instance member test 1", function () {
            $import0.equal(this.calc1Result(), this.test1result);   // (2)
        });
        it("NUnit instance member test 2", function () {
            $import0.equal(this.calc2Result(), this.test2result);   // (2)
        });

        var calc1Result = function () {
            return 1 + 2;
        };
    });

```

 have 2 problems:

1) `test1result` is nowhere to be found (?!) -- I can confirm this only happens when using the plugin (normal Fable compiler works fine). I cannot track where the problem is coming from, yet.

2) Access to instance members are failing in Mocha due to scope of `this`. The calls at (2) should be without `this`. But I can't find a way to translate this.

As a minor aside: why the declaration of `calc1Result` was moved to the bottom of code? It is not a real problem thanks to JavaScript hoisting, but I'm wondering if it is related in some way with the first problem..

**Comment by alfonsogarciacaro** [comment] 2016-04-07 10:07
> 1) `test1result`  is nowhere to be found (?!)

This is because we're ignoring the constructor to avoid the problem reported on top of the issue. Hmm, at the end this is going to be a bit more complicated than expected and we'll have to duplicate some code from Fable's core, but it shouldn't be that difficult.

> 2) Access to instance members are failing in Mocha due to scope of `this`.

Another tricky thing. I'm trying to find the simplest way to solve this: maybe we could compile the class normally but wrap all tests functions in a special method and then create an instance and call this method right after declaring the class (as we did with static constructors). This should fix `this` references. Right now this is working perfectly in my mind but we have to try it in code ;)

> 3) Why the declaration of `calc1Result` was moved to the bottom of code?

No clue at the moment, I'd have to check. Sometimes Babel moves around things specially when flattening `do expressions` but I'd have to debug this particular case to understand the cause.

**Comment by fdcastel** [comment] 2016-04-07 10:17
> because we're ignoring the constructor to avoid the problem reported on top of the issue.

Damn...

> maybe we could compile the class normally but wrap all tests functions in a special method 

Agreed. This would probably be the best way (in a complex set of nested classes and methods the trick of "just removing `this.`" may not work).

We, however, will need to find a workaround for [this guy](https://github.com/fsprojects/Fable/blob/master/src/fable-fsharp/Fable2Babel.fs#L465). (been there, done that :sweat_smile: )

**Comment by fdcastel** [comment] 2016-04-07 10:21
> in a complex set of nested classes and methods

Well... who would be crazy to keep a set of tests like this, anyway? :smile:

**Comment by alfonsogarciacaro** [comment] 2016-04-07 10:33
> We, however, will need to find a workaround for this guy. (been there, done that :sweat_smile: )

I think we shouldn't call `Util.transformModDecls` [here](https://github.com/fsprojects/Fable/blob/master/src/plugins/Fable.Plugins.NUnit.fsx#L85) and [here](https://github.com/fsprojects/Fable/blob/master/src/plugins/Fable.Plugins.NUnit.fsx#L98) but rather replicate the methods and adapt them to needs of the plugin, so we can omit the naming check for test functions :+1:

> in a complex set of nested classes and methods

F# doesn't let you nest classes, only modules (which gave me a headache when parsing TypeScript definitions), so that shouldn't be a problem :)

**Comment by fdcastel** [comment] 2016-04-07 10:44
> but rather replicate the methods and adapt them to needs of the plugin

Ugh...

Or maybe just to add "one more little parameter" to it and avoid to duplicate the code? :sweat_smile: 

I was thinking about the plugin system since your comments in #97. Maybe a revamp? But this is a subject for another thread :)

> F# doesn't let you nest classes

DOH! Of course ;) :+1:

**Comment by fdcastel** [comment] 2016-04-07 10:54
> F# doesn't let you nest classes

On the other hand... This wouldn't make the "just remove `this.` from the calling members" a more appealing (and simpler) option?

**Comment by alfonsogarciacaro** [comment] 2016-04-07 11:08
It can be an option but we'll have some challenges with private variables like `test1result` in your sample. Right now, these variables are not "declared" anywhere, they're just attached to `this` in the constructor.

**Comment by alfonsogarciacaro** [comment] 2016-08-03 07:42
Sorry, I'm closing this as this is not a priority at the moment. If you still need it, @fdcastel, please send a WIP PR and we can work together there :+1:

**Closed by alfonsogarciacaro** 2016-08-03 07:42 UTC
Labels: feature

**Comment by fdcastel** [comment] 2016-08-03 16:40
Yep. Old problem. Very low priority. :+1:
